version: '2'

services:
  front:
      container_name: front
      build:
        context: .
      env_file:
        - '.env'
      ports:
        - "${NODE_PORT}:${NODE_PORT}"
      volumes:
        - ./front/actions:/usr/src/app/actions
        - ./front/components:/usr/src/app/components
        - ./front/constants:/usr/src/app/constants
        - ./front/containers:/usr/src/app/containers
        - ./front/reducers:/usr/src/app/reducers
        - ./front/styles:/usr/src/app/styles
        - ./front/svg:/usr/src/app/svg
        - ./front/utils:/usr/src/app/utils
        - ./front/app.js:/usr/src/app/app.js
        - ./front/Store.js:/usr/src/app/Store.js
        - ./front/dev-server.js:/usr/src/app/dev-server.js
        - ./front/bin:/usr/src/app/bin