export const REQ_CATALOG = 'REQ_CATALOG';
export const SET_ITEMS = 'SET_ITEMS';

export const REQ_CONTACTS = 'REQ_CONTACTS';
export const SET_CONTACTS = 'SET_CONTACTS';

export const REQ_ITEM_PROPERTIES = 'REQ_ITEM_PROPERTIES';
export const SET_ITEM_PROPERTIES = 'SET_ITEM_PROPERTIES';

export const REQ_COLORS = 'REQ_COLORS';
export const SET_COLORS = 'SET_COLORS';

export const REQ_PLANTS = 'REQ_PLANTS';
export const SET_PLANTS = 'SET_PLANTS';

export const REQ_PRODUCTS = 'REQ_PRODUCTS';
export const SET_PRODUCTS = 'SET_PRODUCTS';

export const REQ_ADDITIONAL_ELEMENTS = 'REQ_ADDITIONAL_ELEMENTS';
export const SET_ADDITIONAL_ELEMENTS = 'SET_ADDITIONAL_ELEMENTS';

export const OPEN_MAGNIFYING_POPUP = 'OPEN_MAGNIFYING_POPUP';
export const CLOSE_MAGNIFYING_POPUP = 'CLOSE_MAGNIFYING_POPUP';
